# 這是您的資料庫連線設定檔
# 這是您的資料庫連線設定檔
spring.datasource.url=jdbc:mysql://43.167.207.138:31003/zeabur?serverTimezone=Asia/Taipei
spring.datasource.username=root
spring.datasource.password=J5ZcLz961DfBxY2j3mSlnp4WO07PCKH8
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.sql.init.mode=always